# docker-compose up --build --abort-on-container-exit
version: "3"

services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium_server_works
    ports: ["4440:4444"]
    logging:
      driver: none

  test_runner:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: java_tests_run
    container_name: java_tests_works
    network_mode: "host"
    #depends_on: 
    #  - selenium
    volumes:
      - ./allure-results:/tests/target/allure-results
